# Generated by Django 5.2.1 on 2025-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="underconstruction",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="underconstruction",
            name="uc_duration",
            field=models.CharField(
                blank=True,
                help_text="e.g., '2 hours', 'until 5 PM'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="underconstruction",
            name="uc_note",
            field=models.CharField(
                blank=True,
                help_text="Note to show on maintenance page",
                max_length=255,
                null=True,
            ),
        ),
    ]
